apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simages.serverless.wm775825.info
spec:
  group: serverless.wm775825.info
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: Simage
    plural: simages
  scope: Namespaced
