apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simages.serverless.wm775825.info
spec:
  group: serverless.wm775825.info
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              imageId:
                type: string
              registries:
                type: array
                items:
                  type: string
  names:
    kind: Simage
    plural: simages
    singular: simage
    shortNames:
    - si
  scope: Namespaced
